<?php

declare(strict_types=1);

namespace App\Domain\Rbac;

use App\Models\User;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use RuntimeException;
use Spatie\Permission\PermissionRegistrar;

/**
 * Reads and writes per-location direct permission grants in `model_has_permissions`,
 * directly — mirrors `RoleAssignments` for the same reason: spatie's `permissions()`
 * relation applies `wherePivot(location_id, currentTeam)`, so it can only ever answer
 * "direct grants at the location I'm already standing at", never "direct grants". See
 * docs/05-rbac.md and the CLAUDE.md gotcha this is named after (it was written for
 * `roles()`, but `permissions()` is generated by the same package the same way).
 *
 * Unlike roles, a permission row is global (not per-location) — `model_has_permissions`
 * ties a *location* to an existing permission id via its `location_id` team column, so
 * resolving the permission id by name alone (no location filter) is safe here in a way
 * it is not for `roles`.
 *
 * One home for the sync invariant because it has two callers — `CreateUser` and
 * `UpdateUser` — and it is real logic, not boilerplate worth duplicating.
 */
final class PermissionAssignments
{
    /**
     * Full-set replace: delete this user's direct grants, insert the new set.
     *
     * @param  array<array{location_id: string, permission: string}>  $grants
     * @return array{added: array, removed: array}
     */
    public function sync(User $user, array $grants): array
    {
        $before = $this->current($user);

        DB::table('model_has_permissions')
            ->where('model_type', $user->getMorphClass())
            ->where('model_id', $user->getKey())
            ->delete();

        $rows = [];
        foreach ($grants as $grant) {
            $permissionId = DB::table('permissions')
                ->where('name', $grant['permission'])
                ->where('guard_name', RoleProvisioner::GUARD)
                ->value('id')
                // Not provisioned at all is a seeder/deploy bug, same reasoning as
                // RoleAssignments — loud beats a confusing constraint-violation 500.
                ?? throw new RuntimeException("Permission \"{$grant['permission']}\" is not provisioned.");

            $rows[] = [
                'permission_id' => $permissionId,
                'model_type' => $user->getMorphClass(),
                'model_id' => $user->getKey(),
                'location_id' => $grant['location_id'],
            ];
        }

        if ($rows !== []) {
            DB::table('model_has_permissions')->insert($rows);
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();

        return $this->diff($before, $grants);
    }

    /** @return list<array{location_id: string, permission: string}> */
    public function current(User $user): array
    {
        return DB::table('model_has_permissions')
            ->join('permissions', 'permissions.id', '=', 'model_has_permissions.permission_id')
            ->where('model_has_permissions.model_type', $user->getMorphClass())
            ->where('model_has_permissions.model_id', $user->getKey())
            ->select('model_has_permissions.location_id', 'permissions.name as permission')
            ->get()
            ->map(fn (object $row): array => ['location_id' => $row->location_id, 'permission' => $row->permission])
            ->all();
    }

    /** @return list<array{location_id: string, location_name: string, permission: string}> */
    public function describe(User $user): array
    {
        return $this->rows(fn ($q) => $q->where('model_has_permissions.model_id', $user->getKey()))->all();
    }

    /**
     * Bulk form of `describe()`, one query for every user in the list — the read side of
     * `ListUsers` needs the same join per user; doing it per-user would be an N+1.
     *
     * @param  Collection<int, User>  $users
     * @return Collection<string, list<array{location_id: string, location_name: string, permission: string}>> keyed by user id
     */
    public function describeMany(Collection $users): Collection
    {
        if ($users->isEmpty()) {
            return collect();
        }

        return $this->rows(fn ($q) => $q->whereIn('model_has_permissions.model_id', $users->pluck('id')), withUserId: true)
            ->groupBy('user_id')
            ->map(fn (Collection $rows): array => $rows->map(
                fn (array $row): array => ['location_id' => $row['location_id'], 'location_name' => $row['location_name'], 'permission' => $row['permission']]
            )->values()->all());
    }

    /**
     * @param  callable(Builder): Builder  $scope
     * @return Collection<int, array<string, mixed>>
     */
    private function rows(callable $scope, bool $withUserId = false): Collection
    {
        $query = DB::table('model_has_permissions')
            ->join('permissions', 'permissions.id', '=', 'model_has_permissions.permission_id')
            ->join('locations', 'locations.id', '=', 'model_has_permissions.location_id')
            ->where('model_has_permissions.model_type', (new User)->getMorphClass())
            ->select([
                'model_has_permissions.location_id',
                'locations.name as location_name',
                'permissions.name as permission',
                ...($withUserId ? ['model_has_permissions.model_id as user_id'] : []),
            ]);

        return $scope($query)->get()->map(fn (object $row): array => (array) $row);
    }

    /**
     * @param  list<array{location_id: string, permission: string}>  $before
     * @param  array<array{location_id: string, permission: string}>  $after
     * @return array{added: array, removed: array}
     */
    private function diff(array $before, array $after): array
    {
        $key = fn (array $grant): string => $grant['location_id'].'|'.$grant['permission'];

        $beforeByKey = collect($before)->keyBy($key);
        $afterByKey = collect($after)->keyBy($key);

        $added = $afterByKey->diffKeys($beforeByKey)->values()->all();
        $removed = $beforeByKey->diffKeys($afterByKey)->values()->all();

        return ['added' => $added, 'removed' => $removed];
    }
}
